feature/face recognition
VerticalHeretic/APiP-Project pull request #12
Opened 2022-11-24 12:20 UTC by psztefko

closing #7

2022-11-24 12:23 UTC, psztefko commented on ImageProcessing/ears_drawing.py
> +    right_ear = ear.resize((30, 30))
`REQUIRED` set size depending on face size

2022-11-24 12:26 UTC, VerticalHeretic requested changes

2022-11-24 12:26 UTC, VerticalHeretic commented on ImageProcessing/ears_drawing.py
> +        photo.paste(left_ear, (int(x - w * 3 / 10), y - h), left_ear)
`REQUIRED` magic numbers

2022-11-26 12:44 UTC, VerticalHeretic approved these changes

2022-11-26 13:25 UTC, merged